#!/usr/bin/env bash
prompt_ip(){ local label=$1 v;while true;do read -rp "$label: " v;validate_ipv4 "$v"&&{ printf '%s' "$v";return;};echo 'Invalid IPv4' >&2;done; }
prompt_port(){ local label=$1 def=$2 v;while true;do read -rp "$label [$def]: " v;v=${v:-$def};validate_port "$v"&&{ printf '%s' "$v";return;};echo 'Invalid port' >&2;done; }
cmd_init(){ need_root;mkdir -p "$TF_ETC" "$TF_SECRETS" "$TF_VAR" "$TF_LOG_DIR";local i f sp dh dp tp hp;i=$(prompt_ip 'Iran public IP');f=$(prompt_ip 'Foreign public IP');sp=$(prompt_port 'Iran service port' 2020);read -rp "Foreign destination host [$f]: " dh;dh=${dh:-$f};dp=$(prompt_port 'Foreign destination port' "$sp");tp=$(prompt_port 'Default transport port' 30445);hp=$(prompt_port 'Health probe port' 39091);[[ $sp != $hp && $tp != $hp ]]||die 'service/transport/health ports must be distinct';write_config "$i" "$f" "$sp" "$dh" "$dp" "$tp" "$hp" manual;[[ -s $TF_HEALTH_TOKEN_FILE ]]||rand_token|atomic_write "$TF_HEALTH_TOKEN_FILE" 600;chmod 600 "$TF_CONFIG" "$TF_HEALTH_TOKEN_FILE";history_add action=init result=success;echo "Saved $TF_CONFIG";echo "Destination: $dh:$dp"; }
cmd_config(){ load_config;cat "$TF_CONFIG"; };cmd_drivers(){ echo 'Stable drivers:';list_stable_drivers;echo;echo 'Experimental catalog:';list_experimental_drivers; }
cmd_deploy(){ need_root;local d=${1:-} role=${2:-};[[ -n $d ]]||die 'usage: tunnelforge deploy DRIVER iran|foreign';[[ $role =~ ^(iran|foreign)$ ]]||die 'role must be iran|foreign';load_config;load_driver "$d";if [[ -f $TF_STATE ]];then local old oldrole;old=$(state_get driver);oldrole=$(state_get role);if [[ $old != "$d" || $oldrole != "$role" ]];then load_driver "$old";driver_cleanup "$oldrole"||true;state_clear;load_driver "$d";fi;fi;history_add action=deploy_start driver="$d" role="$role" result=started;local ok=0;trap 'if ((ok==0));then rollback_driver "$d" "$role";fi' ERR INT TERM;driver_preflight "$role";driver_install "$role";driver_configure "$role";driver_start "$role";sleep 1;driver_health "$role";state_set driver="$d" role="$role" deployed_at="$(date -Is)" user_verified=unknown h3=$([[ $role == iran ]]&&echo pass||echo n_a);ok=1;trap - ERR INT TERM;history_add action=deploy driver="$d" role="$role" result=success;log INFO "deployment healthy driver=$d role=$role"; }
cmd_status(){ load_config;[[ -f $TF_STATE ]]||{ echo 'No active deployment';return;};local d role uv;d=$(state_get driver);role=$(state_get role);uv=$(state_get user_verified);load_driver "$d";printf 'TunnelForge\nDriver       %s\nRole         %s\nIran         %s:%s\nForeign      %s\nDestination  %s:%s\n\n' "$d" "$role" "$IRAN_IP" "$SERVICE_PORT" "$FOREIGN_IP" "$DESTINATION_HOST" "$DESTINATION_PORT";driver_status "$role"&&echo 'H0 Process        OK'||echo 'H0 Process        FAIL';if [[ $role == iran ]];then health_h1 "$SERVICE_PORT"&&echo "H1 Listener       OK :$SERVICE_PORT"||echo 'H1 Listener       FAIL';if [[ $d == gost || $d == wstunnel ]];then ss -Hnt 2>/dev/null|grep -q "$FOREIGN_IP:$TRANSPORT_PORT"&&echo "H2 Transport      OK :$TRANSPORT_PORT"||echo 'H2 Transport      FAIL';elif [[ $d == gre ]];then ping -c1 -W1 10.202.0.2 >/dev/null 2>&1&&echo 'H2 Transport      OK GRE'||echo 'H2 Transport      FAIL GRE';else echo 'H2 Transport      N/A direct relay';fi;health_h3 >/dev/null 2>&1&&echo 'H3 Data path      OK'||echo 'H3 Data path      FAIL';echo 'H4 Application    UNKNOWN (test on Foreign / orchestrated)';else health_h1 "$HEALTH_PORT"&&echo "H1 Listener       OK health:$HEALTH_PORT"||echo 'H1 Listener       role-specific';echo 'H2 Transport      ready for Iran';echo 'H3 Data path      tested from Iran';health_destination&&echo 'H4 Application    TCP_ACCEPT'||echo 'H4 Application    FAIL';fi;printf 'H5 User verified  %s\n' "${uv^^}"; }
cmd_test(){ load_config;[[ -f $TF_STATE ]]||die 'no active deployment';[[ $(state_get role) == iran ]]||die 'run data-path test on Iran role';echo 'H3 authenticated data-path probe:';health_h3;echo 'H4 is not inferred from the Iran listener. Run `tunnelforge app-test` on Foreign or use orchestrated mode.'; }
cmd_app_test(){ load_config;[[ -f $TF_STATE ]]||die 'no active deployment';[[ $(state_get role) == foreign ]]||die 'app-test must run on Foreign role';echo "H4 destination probe: $DESTINATION_HOST:$DESTINATION_PORT";health_destination&&echo 'ok=true'||{ echo 'ok=false';return 1;}; }
cmd_verify(){ need_root;[[ ${1:-} =~ ^(yes|no)$ ]]||die 'usage: tunnelforge verify yes|no';[[ -f $TF_STATE ]]||die 'no active deployment';state_set user_verified="$1";history_add action=verify driver="$(state_get driver)" role="$(state_get role)" result="$1";echo "H5 recorded: $1"; }
cmd_history(){ [[ -f $TF_HISTORY ]]&&cat "$TF_HISTORY"||true; }
cmd_commands(){ load_config;local d=${1:-};load_driver "$d" >/dev/null;local cfg tok;cfg=$(base64 -w0 "$TF_CONFIG");tok=$(base64 -w0 "$TF_HEALTH_TOKEN_FILE");cat <<EOF
# Sensitive: embedded health token. Do not publish.
Foreign Command:
sudo tunnelforge import-runtime '$cfg' '$tok' && sudo tunnelforge deploy $d foreign

Iran Command:
sudo tunnelforge import-runtime '$cfg' '$tok' && sudo tunnelforge deploy $d iran
EOF
}
cmd_import_runtime(){ need_root;local cfg=${1:-} tok=${2:-};[[ -n $cfg && -n $tok ]]||die 'missing runtime bundle';mkdir -p "$TF_ETC" "$TF_SECRETS";printf '%s' "$cfg"|base64 -d|atomic_write "$TF_CONFIG" 600;printf '%s' "$tok"|base64 -d|atomic_write "$TF_HEALTH_TOKEN_FILE" 600;load_config;echo 'Runtime imported'; }
cmd_orchestrate(){ load_config;local d=${1:-};load_driver "$d" >/dev/null;[[ -s $TF_HEALTH_TOKEN_FILE ]]||die 'missing health token';need_cmd ssh;remote_sync_runtime foreign;remote_exec foreign "sudo tunnelforge deploy '$d' foreign";remote_sync_runtime iran;if ! remote_exec iran "sudo tunnelforge deploy '$d' iran";then remote_exec iran 'sudo tunnelforge down'||true;remote_exec foreign 'sudo tunnelforge down'||true;return 1;fi;remote_exec iran 'sudo tunnelforge test';remote_exec foreign 'sudo tunnelforge app-test';echo 'Orchestrated deployment passed H3 and H4. H5 still requires real user verification.'; }
stable_order=(gre haproxy rinetd socat gost wstunnel)
cmd_next(){ load_config;[[ -f $TF_STATE ]]||die 'no active deployment';local cur i next='';cur=$(state_get driver);for i in "${!stable_order[@]}";do if [[ ${stable_order[$i]} == "$cur" ]];then next=${stable_order[$(((i+1)%${#stable_order[@]}))]};break;fi;done;[[ -n $next ]]||next=${stable_order[0]};echo "Next driver: $next";[[ $MODE == orchestrated ]]&&cmd_orchestrate "$next"||echo "Manual mode: tunnelforge commands $next"; }
cmd_auto(){ load_config;[[ $MODE == orchestrated ]]||die 'auto requires mode=orchestrated';local d;for d in "${stable_order[@]}";do echo "=== Trying $d ===";if cmd_orchestrate "$d";then echo "TECHNICALLY WORKING: $d (H3/H4 pass; H5 still explicit)";history_add action=auto driver="$d" result=pass;return 0;fi;history_add action=auto driver="$d" result=fail;remote_exec iran 'sudo tunnelforge down'||true;remote_exec foreign 'sudo tunnelforge down'||true;done;die 'no stable driver passed H3/H4'; }
