mode = "manual"
iran_ip = "203.0.113.10"
foreign_ip = "198.51.100.20"
service_port = 2020
destination_host = "198.51.100.20"
destination_port = 2020
transport_port = 30445
health_port = 39091
protocol = "tcp"
ssh_user = "root"
ssh_port = 22
ssh_key = ""
expert_mode = false
